version: '3'

services:
  shape_bot:
    build: .
    container_name: telegram_shape_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Store database outside container
    env_file:
      - .env  # Load variables from .env file
    environment:
      # Set defaults for optional variables
      - SHAPES_API_URL=${SHAPES_API_URL:-https://api.shapes.inc/v1/}
      - DB_FILE=data/shape_bot.db
    command: ["./start_bot.sh"]  # Use our start script